{
 "title": "Critical Vulnerability Security Dashboard",
 "tags": [
  "security",
  "trivy",
  "critical"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Critical Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Workloads Affected by Critical Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(trivy_image_vulnerabilities{severity=\"Critical\"} > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Critical Workloads & Container Images Summary",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "trivy_image_vulnerabilities{severity=\"Critical\"} > 0"
    }
   ]
  }
 ]
}